region: westus # CHANGE ME
hostname: mycluster.example.org # CHANGE ME
certificate_email: john.doe@example.org # CHANGE ME

azure:
  subscription_id: UUID # CHANGE ME
  resource_group_name: my_resource_group # CHANGE ME
  dns_zone: example.org # CHANGE ME
  user_assigned_identity_client_id: UUID # CHANGE ME

controller:
  image: docker.io/denoland/cluster-controller:v0.0.1
  isolate_worker:
    image: docker.io/denoland/cluster-isolate-worker:v0.0.1

proxy:
  image: docker.io/denoland/cluster-proxy:v0.0.1

lscached:
  image: docker.io/denoland/cluster-lscached:v0.0.1

blob:
  azure:
    storage_account: mystorageaccount # CHANGE ME
    storage_account_endpoint: https://mystorageaccount.blob.core.windows.net # CHANGE ME
    credentials: supersecret credentials # CHANGE ME
    code_storage_bucket: deployments
    cache_storage_bucket: cache
    hostmap_storage_bucket: deployments
  # s3:
  #   access_key: AKIAEXAMPLE
  #   secret_key: SECRETKEYEXAMPLE
  #   code_storage_bucket: code-storage
  #   cache_storage_bucket: cache-storage
