# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

provider: azure
region: westus # CHANGE ME
hostname: mycluster.example.org # CHANGE ME

# The certificate email will be associated with the TLS certificate provisioned
# through Let's Encrypt.
certificate_email: foo@example.org # CHANGE ME

azure:
  subscription_id: UUID # CHANGE ME
  resource_group_name: my_resource_group # CHANGE ME
  dns_zone: example.org # CHANGE ME
  user_assigned_identity_client_id: UUID # CHANGE ME

blob:
  minio:
    cache_storage_bucket: cache
    code_storage_bucket: deployments
    hostmap_storage_bucket: deployments

# Uncomment the following block to send logs to an OTLP endpoint.
# otlp:
#   endpoint: https://otlp-gateway-prod-us-east-0.grafana.net/otlp
#   auth:
#     authenticator: basicauth/otlp
#     username: "103456"
#     password: "ghc_xxx"

controller:
  serviceaccount_annotations: {}

proxy:
  serviceaccount_annotations: {}
