# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    {{- range $k, $v := .Values.controller.serviceaccount_annotations }}
    {{ $k }}: {{ $v }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
  name: controller
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-binding
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deno-metrics
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - get
      - watch
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes/metrics
    verbs:
      - get
  - nonResourceURLs:
      - /metrics
      - /metrics/cadvisor
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations: {}
  name: deno-metrics-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deno-metrics
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  foo: bar
kind: ConfigMap
metadata:
  name: pods-config
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-auto-scaler-state
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-cluster-info
  namespace: {{ .Release.Namespace }}
data:
  "api_endpoint": "https://api.{{ .Values.hostname }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: primary-controller-lock
  namespace: {{ .Release.Namespace }}
  labels:
    app: primary-controller-lock
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-credentials-init"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-credentials-init"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: OnFailure
      serviceAccountName: controller
      containers:
      - name: controller
        image: {{ default "docker.io/denoland" .Values.docker_base_path }}/{{ default "cluster" .Values.docker_image_prefix }}-controller:{{ default .Chart.AppVersion (.Values.controller).version }}
        env:
          - name: DO_CREDENTIALS_INIT
            value: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controller
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: controller
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/provisioner-name
                operator: DoesNotExist
            {{- if eq .Values.provider "aws" }}
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - static
            {{- end }}
      containers:
      - envFrom:
        - secretRef:
            name: controller-credentials
        env:
        - name: MIN_ISOLATE_WORKERS_REPLICAS
          value: {{ quote (default 4 .Values.controller.min_isolate_workers_replicas) }}
        - name: MAX_ISOLATE_WORKERS_REPLICAS
          value: {{ quote (default 10 .Values.controller.max_isolate_workers_replicas) }}
        - name: ISOLATE_WORKER_CONTAINER_IMAGE
          value: {{ default "docker.io/denoland" .Values.docker_base_path }}/{{ default "cluster" .Values.docker_image_prefix }}-isolate-worker:{{ default .Chart.AppVersion (.Values.controller).isolate_worker_version }}
        - name: CONTROLLER_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: CONTROLLER_POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SVMC_ENDPOINT
          value: svmcd.{{ .Release.Namespace }}.svc.cluster.local:7293
        - name: LSC_ENDPOINT
          value: http://lscached-serve.{{ .Release.Namespace }}.svc.cluster.local:4522
        - name: OIDC_ISS
          value: http://controller.{{ .Release.Namespace }}.svc.cluster.local:4000
        - name: KUBELET_TLS_CA
          valueFrom:
            configMapKeyRef:
              name: kube-root-ca.crt
              key: ca.crt
        - name: AWS_REGION
          value: {{ .Values.region }}
        - name: CLUSTER_PROVIDER
          value: {{ .Values.provider }}
        - name: CLUSTER_REGION
          value: {{ .Values.region }}
        {{- if .Values.blob.minio }}
        - name: S3_ENDPOINT
          value: http://minio.{{ .Release.Namespace }}.svc.cluster.local:9000
        - name: AWS_EC2_METADATA_DISABLED
          value: "true"
        - name: AWS_ACCESS_KEY_ID
          value: minioadmin
        - name: AWS_SECRET_ACCESS_KEY
          value: minioadmin
        - name: HOSTMAP_SOURCE_default
          value: '{"hostname":"*","s3Endpoint":"http://minio.{{ .Release.Namespace }}.svc.cluster.local:9000","s3Bucket":{{ quote .Values.blob.minio.code_storage_bucket }},"s3Region":{{ quote .Values.region }},"s3Prefix":"hostmap/"}'
        {{- else if .Values.blob.s3 }}
        - name: HOSTMAP_SOURCE_default
          value: '{"hostname":"*","s3Bucket":{{ quote .Values.blob.s3.code_storage_bucket }},"s3Region":{{ quote .Values.region }},"s3Prefix":"hostmap/"}'
        {{- end }}
        {{- range .Values.controller.env }}
        - name: {{ .name }}
          {{- /* Must convert to yaml, indent and trim to support multiline strings in values */}}
          value: {{ .value | toYaml | indent 10 | trim }}
        {{- end }}
        image: {{ default "docker.io/denoland" .Values.docker_base_path }}/{{ default "cluster" .Values.docker_image_prefix }}-controller:{{ default .Chart.AppVersion (.Values.controller).version }}
        imagePullPolicy: IfNotPresent
        name: controller
        ports:
        - containerPort: 4000
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      priorityClassName: deno-system-critical
      serviceAccount: controller
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: controller
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: 4000
  selector:
    app: controller
  type: ClusterIP
