# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: isolate-worker-pdb
  namespace: {{ .Release.Namespace }}
spec:
  # minAvailable is dynamically set by the controller
  minAvailable: 0
  selector:
    matchLabels:
      app: isolate-worker
