# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

{{- range $index, $pool := .Values.isolate_pools }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: isolate-worker-pdb-{{ $pool.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  minAvailable: {{ $pool.min_workers_replicas | default 3 }}
  selector:
    matchLabels:
      app: isolate-worker
      deno.com/pool: {{ $pool.name }}
{{- end }}