# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

{{- if eq .Values.provider "aws" }}
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: isolate-workers
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  amiFamily: AL2023
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  role: karpenter-node-{{ .Values.cluster_name }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.cluster_name }}
        Name: {{ .Values.cluster_name }}-node
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.cluster_name }}
  tags:
    karpenter.sh/discovery: {{ .Values.cluster_name }}
  kubelet:
    maxPods: {{ .Values.karpenter.ec2NodeClass.isolateWorkers.kubelet.maxPods }}
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  amiFamily: AL2023
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  role: karpenter-node-{{ .Values.cluster_name }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.cluster_name }}
        Name: {{ .Values.cluster_name }}-node
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.cluster_name }}
  tags:
    karpenter.sh/discovery: {{ .Values.cluster_name }}
---
{{- /* Create NodePools for each isolate pool */ -}}
{{- range $index, $poolConfig := .Values.isolate_pools }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: isolate-workers-{{ $poolConfig.name }}-fallback
spec:
  weight: 1
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        {{- range $key, $value := $poolConfig.node_labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      expireAfter: {{ $.Values.karpenter.nodePool.isolateWorkers.expireAfter }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: isolate-workers
      taints:
      - key: deno.com/workloads
        value: isolate-workers
        effect: NoSchedule
      {{- range $key, $value := $poolConfig.node_labels }}
      - key: {{ $key }}
        value: {{ $value }}
        effect: NoSchedule
      {{- end }}
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c8g.xlarge
        - c7g.xlarge
        - c6g.xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      {{- if $.Values.karpenter.nodePool.isolateWorkers.single_az.enabled }}
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - {{ $.Values.karpenter.nodePool.isolateWorkers.single_az.zoneName }}
      {{- end }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: isolate-workers-{{ $poolConfig.name }}-preferred
spec:
  weight: 50
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        {{- range $key, $value := $poolConfig.node_labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      expireAfter: {{ $.Values.karpenter.nodePool.isolateWorkers.expireAfter }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: isolate-workers
      taints:
      {{- range $key, $value := $poolConfig.node_labels }}
      - key: {{ $key }}
        value: {{ $value }}
        effect: NoSchedule
      {{- end }}
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      {{- if $poolConfig.metal }}
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c8g.metal-24xl
        - c7g.metal
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      {{- else }}
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c8g.xlarge
        - c7g.xlarge
        - c6g.xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      {{- end }}
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      {{- if $.Values.karpenter.nodePool.isolateWorkers.single_az.enabled }}
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - {{ $.Values.karpenter.nodePool.isolateWorkers.single_az.zoneName }}
      {{- end }}
{{- end }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: stable-workload
spec:
  weight: 100
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        deno.com/workloads: stable
    spec:
      limits:
        cpu: 10
        memory: 100Gi
      expireAfter: {{ .Values.karpenter.nodePool.stableWorkload.expireAfter }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      taints:
      - key: deno.com/workloads
        value: nextgen
        effect: NoSchedule
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "5"
      {{- if .Values.karpenter.nodePool.stableWorkload.single_az.enabled }}
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - {{ .Values.karpenter.nodePool.stableWorkload.single_az.zoneName }}
      {{- end }}
{{- end }}