# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

{{- if eq .Values.provider "aws" }}
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: isolate-workers
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  role: karpenter-node-{{ .Values.cluster_name }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.cluster_name }}
        Name: {{ .Values.cluster_name }}-node
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.cluster_name }}
  tags:
    karpenter.sh/discovery: {{ .Values.cluster_name }}
  kubelet:
    maxPods: {{ .Values.karpenter.ec2NodeClass.isolateWorkers.kubelet.maxPods }}
  userData: |
    # Tell BottleRocket to reboot when it is necessary for certain changes
    # made below (in particular: 'systemd.unified_cgroup_hierarchy') to take
    # effect.
    [settings.boot]
    reboot-to-reconcile = true

    # Use cgroups v2 (enabled by default in newer versions, but explicitly set for clarity)
    [settings.boot.init]
    "systemd.unified_cgroup_hierarchy" = ["1"]

    # On BottleRocket, `max_user_namespaces` is set to 0 by default. Bump it
    # to 30985, which matches the default limit for `max_mnt_namespaces`.
    [settings.kernel.sysctl]
    "user.max_user_namespaces" = "30985"

    # We've been hitting the registryPullQPS limit. Hence, removing it
    [settings.kubernetes]
    "registry-qps" = 0

    [settings.kernel]
    lockdown = "none"

    [settings.boot.kernel-parameters]
    "preempt" = ["full"]
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  role: karpenter-node-{{ .Values.cluster_name }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.cluster_name }}
        Name: {{ .Values.cluster_name }}-node
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.cluster_name }}
  tags:
    karpenter.sh/discovery: {{ .Values.cluster_name }}
  userData: |
    # Tell BottleRocket to reboot when it is necessary for certain changes
    [settings.boot]
    reboot-to-reconcile = true

    # On BottleRocket, `max_user_namespaces` is set to 0 by default. Bump it
    # to 30985, which matches the default limit for `max_mnt_namespaces`.
    [settings.kernel.sysctl]
    "user.max_user_namespaces" = "30985"

    # We've been hitting the registryPullQPS limit. Hence, removing it
    [settings.kubernetes]
    "registry-qps" = 0

    [settings.kernel]
    lockdown = "none"

    [settings.boot.kernel-parameters]
    "preempt" = ["full"]
---
{{- /* Create NodePools for each isolate pool */ -}}
{{- range $index, $poolConfig := .Values.isolate_pools }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: isolate-workers-{{ $poolConfig.name }}-fallback
spec:
  weight: 1
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        {{- range $key, $value := $poolConfig.node_labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      expireAfter: {{ $.Values.karpenter.nodePool.isolateWorkers.expireAfter }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: isolate-workers
      taints:
      - key: deno.com/workloads
        value: isolate-workers
        effect: NoSchedule
      {{- range $key, $value := $poolConfig.node_labels }}
      - key: {{ $key }}
        value: {{ $value }}
        effect: NoSchedule
      {{- end }}
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      {{- if $.Values.karpenter.nodePool.isolateWorkers.single_az.enabled }}
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - {{ $.Values.karpenter.nodePool.isolateWorkers.single_az.zoneName }}
      {{- end }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: isolate-workers-{{ $poolConfig.name }}-preferred
spec:
  weight: 50
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        {{- range $key, $value := $poolConfig.node_labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      expireAfter: {{ $.Values.karpenter.nodePool.isolateWorkers.expireAfter }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: isolate-workers
      taints:
      {{- range $key, $value := $poolConfig.node_labels }}
      - key: {{ $key }}
        value: {{ $value }}
        effect: NoSchedule
      {{- end }}
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "5"
      {{- if $.Values.karpenter.nodePool.isolateWorkers.single_az.enabled }}
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - {{ $.Values.karpenter.nodePool.isolateWorkers.single_az.zoneName }}
      {{- end }}
{{- end }}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: stable-workload
spec:
  weight: 100
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        deno.com/workloads: stable
    spec:
      limits:
        cpu: 10
        memory: 100Gi
      expireAfter: {{ .Values.karpenter.nodePool.stableWorkload.expireAfter }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      taints:
      - key: deno.com/workloads
        value: nextgen
        effect: NoSchedule
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "5"
      {{- if .Values.karpenter.nodePool.stableWorkload.single_az.enabled }}
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - {{ .Values.karpenter.nodePool.stableWorkload.single_az.zoneName }}
      {{- end }}
{{- end }}