# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: main
  namespace: {{ .Release.Namespace }}
spec:
  args:
    feature-gates: -component.UseLocalHostAsDefaultHost,-confmap.strictlyTypedInput
  autoscaler:
    maxReplicas: 10
    minReplicas: 1
    targetMemoryUtilization: 70
  config:
    exporters:
      nop: {}
      {{- if .Values.otlp }}
      otlphttp:
        endpoint: "{{ .Values.otlp.endpoint }}"
        {{- if .Values.otlp.auth }}
        auth:
          authenticator: {{ .Values.otlp.auth.authenticator }}
        {{- end }}
      {{- end }}
    extensions:
      health_check: {}
      zpages: {}
      {{- if and (.Values.otlp) (.Values.otlp.auth) (eq .Values.otlp.auth.authenticator "basicauth/otlp") }}
      basicauth/otlp:
        client_auth:
          username: '{{ .Values.otlp.auth.username }}'
          password: '{{ .Values.otlp.auth.password }}'
      {{- end }}
    processors:
      batch: {}
      resource:
        attributes:
        - action: upsert
          key: cloud.provider
          value: {{ quote .Values.provider }}
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      extensions:
        - health_check
        - zpages
        {{- if and (.Values.otlp) (.Values.otlp.auth) (eq .Values.otlp.auth.authenticator "basicauth/otlp") }}
        - basicauth/otlp
        {{- end }}
      pipelines:
        logs:
          exporters:
            {{- if .Values.otlp }}
            - otlphttp
            {{- else }}
            - nop
            {{- end }}
          processors: [batch, resource]
          receivers: [otlp]
        traces:
          exporters:
            {{- if .Values.otlp }}
            - otlphttp
            {{- else }}
            - nop
            {{- end }}
          processors: [batch, resource]
          receivers: [otlp]
  image: otel/opentelemetry-collector-contrib:0.105.0
  mode: deployment
  ports:
  - name: otlpgrpc
    port: 4317
  - name: otlphttp
    port: 4318
  - name: metrics
    port: 8888
  - name: healthcheck
    port: 13133
  - name: zpages
    port: 55679
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 300m
      memory: 512Mi