# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

apiVersion: v1
kind: ConfigMap
metadata:
  name: post-install-script-wait-for-cluster-id
  namespace: {{ .Release.Namespace }}
data:
  "script.sh": |
    while ! kubectl get configmap controller-cluster-info -o jsonpath='{.data.cluster_setup_url}' | grep -q .; do
      echo "Waiting for key cluster_setup_url to be set in ConfigMap controller-cluster-info..."
      sleep 2
    done
    echo "Key cluster_setup_url is now set in ConfigMap controller-cluster-info."

---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-wait-for-cluster-id"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 600
  template:
    metadata:
      name: "{{ .Release.Name }}-wait-for"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccountName: controller
      containers:
      - name: post-install-job
        image: docker.io/bitnami/kubectl:latest
        command: ["/bin/bash", "/post-install-script/script.sh"]
        volumeMounts:
          - name: post-install-script
            mountPath: /post-install-script
            readOnly: true
      volumes:
        - name: post-install-script
          configMap:
            name: post-install-script-wait-for-cluster-id
