# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: svmcd
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: svmcd
  serviceName: "svmcd"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: svmcd
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: {{ default "ghcr.io/denoland" .Values.docker_base_path }}/{{ default "cluster" .Values.docker_image_prefix }}-lscached:{{ default .Chart.AppVersion (.Values.lscached).version }}
        imagePullPolicy: IfNotPresent
        name: svmcd
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 7293
          name: external
          protocol: UDP
        args:
        - /svmcd
        - --addr=[::]:7293
        envFrom:
        - secretRef:
            name: svmcd-credentials
        env:
        - name: RUST_LOG
          value: info
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: svmcd
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 7293
      protocol: UDP
      targetPort: 7293
  selector:
    app: svmcd
  type: ClusterIP
