# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.
{{- if .Values.enable_ublk }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ublk-loader
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ublk-loader
  template:
    metadata:
      labels:
        app: ublk-loader
    spec:
      containers:
      - image: {{ default "ghcr.io/denoland" .Values.docker_base_path }}/{{ default "cluster" .Values.docker_image_prefix }}-isolate-worker:{{ default .Chart.AppVersion (.Values.controller).isolate_worker_version }}
        imagePullPolicy: IfNotPresent
        name: ublk-loader-container
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: UBLK_LOADER
          value: "1"
        securityContext:
          privileged: true
        volumeMounts:
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        - name: src
          mountPath: /usr/src
          readOnly: true
      volumes:
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: src
          hostPath:
            path: /usr/src
            type: Directory
      restartPolicy: Always
      tolerations:
      - key: "kubernetes.io/arch"
        operator: Exists
        effect: NoSchedule
      - key: "deno.com/workloads"
        operator: Exists
        effect: NoSchedule
      - key: "deno.com/pool"
        operator: Exists
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "deno.com/pool"
                    operator: Exists
{{- end }}
