# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

# The cloud provider deno-cluster is deployed to.
# One of `aws`, `azure`
provider: aws # CHANGE ME
region: westus # CHANGE ME
hostname: mycluster.deno.co # CHANGE ME

# The certificate email will be used to provision a TLS certificate with
# Let's Encrypt
# certificate_email: foo@example.org # CHANGE ME

# The following block is used to provision Let's Encrypt certificates on Azure.
# azure:
#   subscription_id: 68245e99-8e6b-43ff-931c-0a895801acad
#   resource_group_name: deno-cluster-01
#   dns_zone: deno-cluster.net
#   # The User Assigned Identity Client ID is used to allow cert-manager to edit
#   # DNS Zone records.
#   user_assigned_identity_client_id: cccdafcd-7078-461d-a093-9d1f306efbe4

controller:
  image: ghcr.io/denoland/cluster-controller:v0.0.17
  # serviceaccount_annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::329599618741:role/...
  env:
    - name: ISOLATE_WORKER_CONTAINER_IMAGE
      value: ghcr.io/denoland/cluster-isolate-worker:v0.0.17
    - name: ISOLATE_WORKER_MIN_CPU_PER_NODE
      value: "1500m"
    # - name: OTEL_EXPORTER_OTLP_ENDPOINT
    #   value: http://main-collector.default.svc.cluster.local:4317

proxy:
  image: ghcr.io/denoland/cluster-proxy:v0.0.17
  # The service ports override which port the Service resource for the proxy is
  # opened. This is used for example in minikube to be able to expose the port
  # on localhost.
  #   https_service_port: 4443
  #   http_service_port: 4080
  #   http_redirect_port: 4081
  # Enable proxy protocol support for client IP preservation. When enabled, the
  # proxy will expect and parse the PROXY protocol header.
  #   use_proxy_protocol: true
  # Additional annotations to add to the proxy service account.
  #   serviceaccount_annotations:
  #     eks.amazonaws.com/role-arn: arn:aws:iam::329599618741:role/...
  env:
    # - name: OTEL_EXPORTER_OTLP_ENDPOINT
    #   value: http://main-collector.default.svc.cluster.local:4317

# This is used to assign different permissions to a set of public keys used in
# JWT auth .
auth:
  # Turning this flag on allows requests to bypass the auth when a JWT token is
  # not presented in the requests.
  allow_bypass: false
  # A list of different accounts and their EC public keys.
  accounts:
    - name: user123
      publicKey: |
        -----BEGIN PUBLIC KEY-----
        MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEofG+JaGlIKAx3qF4qZmJz3/y3xIwm+nU
        0wFHMII6tB77sUqXMjPXY7OVgExkYAP3EtsxLxOslq7PduhfPl5R5g==
        -----END PUBLIC KEY-----
      scopes: "appconfig"
    - name: admin
      publicKey: |
        -----BEGIN PUBLIC KEY-----
        MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEofG+JaGlIKAx3qF4qZmJz3/y3xIwm+nU
        0wFHMII6tB77sUqXMjPXY7OVgExkYAP3EtsxLxOslq7PduhfPl5R5g==
        -----END PUBLIC KEY-----
      scopes: "*"

lscached:
  image: ghcr.io/denoland/cluster-lscached:v0.0.17

blob:
  # Uncomment the following block to configure blob storage on AWS
  #   s3:
  #     access_key: AKIAEXAMPLE
  #     secret_key: SECRETKEYEXAMPLE
  #     code_storage_bucket: code-storage
  #     cache_storage_bucket: cache-storage

  # Uncomment the following block to configure blob storage in-cluster with Minio
  minio:
    code_storage_bucket: deployments
    cache_storage_bucket: cache

isolate_pools:
  - name: default
    target_free_pool_ratio: 0.5
    min_workers_replicas: 4
    max_workers_replicas: 10
    worker_cpu_request: "15m"
    worker_memory_request: "32M"
    worker_memory_limit: "1024M"
    worker_min_cpu_per_node: "1500m"
    idle_timeout_ms: 60000
    cluster_util_source: "mr"
    cluster_cpu_pct_target: 0.6
    cluster_memory_pct_target: 0.6
    worker_pods_grace_period_sec: 120
    initial_request_stream_concurrency: 10
    max_request_stream_concurrency: 100
    node_labels:
      deno.com/pool: default
