# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

# The cloud provider deno-cluster is deployed to.
# One of `aws`, `azure`
provider: aws # CHANGE ME
region: westus # CHANGE ME
hostname: mycluster.deno.co # CHANGE ME

# The certificate email will be used to provision a TLS certificate with
# Let's Encrypt
# certificate_email: foo@example.org # CHANGE ME

# The following block is used to provision Let's Encrypt certificates on Azure.
# azure:
#   subscription_id: 68245e99-8e6b-43ff-931c-0a895801acad
#   resource_group_name: deno-cluster-01
#   dns_zone: deno-cluster.net
#   # The User Assigned Identity Client ID is used to allow cert-manager to edit
#   # DNS Zone records.
#   user_assigned_identity_client_id: cccdafcd-7078-461d-a093-9d1f306efbe4

# The following block is used to configure AWS-specific resources such as the
# NLB Load Balancer.
# aws:
#   subnet: star-shaped-hole-dev-subnet1
#   nlb: star-shaped-hole-dev-nlb

controller:
  image: ghcr.io/denoland/cluster-controller:v0.0.17
  # serviceaccount_annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::329599618741:role/...
  # min_isolate_workers_replicas: 10
  # max_isolate_workers_replicas: 100
  # isolate_worker_cpu_request: 15m
  # isolate_worker_min_cpu_per_node: 1500m
  env:
    - name: ISOLATE_WORKER_CONTAINER_IMAGE
      value: ghcr.io/denoland/cluster-isolate-worker:v0.0.17
    # - name: ISOLATE_TARGET_FREE_POOL_RATIO
    #   value: "0.5"
    # - name: NODE_METRICS_SELECTOR
    #   value: "karpenter.sh/provisioner-name=default"
    # - name: CLUSTER_CPU_PCT_TARGET
    #   value: "0.6"
    # - name: CLUSTER_MEMORY_PCT_TARGET
    #   value: "0.6"
    # - name: OTEL_EXPORTER_OTLP_ENDPOINT
    #   value: http://main-collector.default.svc.cluster.local:4317

proxy:
  image: ghcr.io/denoland/cluster-proxy:v0.0.17
  # The service ports override which port the Service resource for the proxy is
  # opened. This is used for example in minikube to be able to expose the port
  # on localhost.
  # https_service_port: 4443
  # http_service_port: 4080
  # http_redirect_port: 4081
  # serviceaccount_annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::329599618741:role/...
  env:
    # - name: OTEL_EXPORTER_OTLP_ENDPOINT
    #   value: http://main-collector.default.svc.cluster.local:4317

# This is used to assign different permissions to a set of public keys used in
# JWT auth .
auth:
  # Turning this flag on allows requests to bypass the auth when a JWT token is
  # not presented in the requests.
  allow_bypass: false
  # A list of different accounts and their EC public keys.
  accounts:
    - name: user123
      publicKey: |
        -----BEGIN PUBLIC KEY-----
        MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEofG+JaGlIKAx3qF4qZmJz3/y3xIwm+nU
        0wFHMII6tB77sUqXMjPXY7OVgExkYAP3EtsxLxOslq7PduhfPl5R5g==
        -----END PUBLIC KEY-----
      scopes: "appconfig"
    - name: admin
      publicKey: |
        -----BEGIN PUBLIC KEY-----
        MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEofG+JaGlIKAx3qF4qZmJz3/y3xIwm+nU
        0wFHMII6tB77sUqXMjPXY7OVgExkYAP3EtsxLxOslq7PduhfPl5R5g==
        -----END PUBLIC KEY-----
      scopes: "*"

lscached:
  image: ghcr.io/denoland/cluster-lscached:v0.0.17

blob:
  # Uncomment the following block to configure blob storage on AWS
  # s3:
  #   access_key: AKIAEXAMPLE
  #   secret_key: SECRETKEYEXAMPLE
  #   code_storage_bucket: code-storage
  #   cache_storage_bucket: cache-storage

  # Uncomment the following block to configure blob storage in-cluster with Minio
  minio:
    code_storage_bucket: deployments
    cache_storage_bucket: cache
