# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

priorityClasses:
  enabled: true

storageClasses:
  enabled: true

clusterRBAC:
  enabled: true

controller:
  isolate_worker:
    tolerations:
    - key: isolate-worker
      operator: Exists
      effect: NoSchedule
    node_affinities:
    - key: karpenter.sh/provisioner-name
      operator: In
      values: ['default']


dnsmasq:
  upstreamServers: 
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - 1.0.0.1
  resources: 
    requests:
        cpu: 100m
        memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  nodeSelector: {}

compute_pops:
  - self