# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

priorityClasses:
  enabled: true

storageClasses:
  enabled: true

clusterRBAC:
  enabled: true

# Isolate pool configuration
# Each pool is defined as an object in the array with its own properties including a name field
isolate_pools:
  - name: default
    target_free_pool_ratio: 0.5        # Target ratio of free pods to total pods
    min_workers_replicas: 4            # Minimum number of worker replicas
    max_workers_replicas: 10           # Maximum number of worker replicas
    worker_cpu_request: "15m"          # CPU request for worker pods
    worker_memory_request: "32M"       # Memory request for worker pods
    worker_memory_limit: "1024M"       # Memory limit for worker pods
    worker_min_cpu_per_node: "1500m"   # Minimum CPU per node for worker pods
    idle_timeout_ms: 60000             # Idle timeout in milliseconds
    cluster_util_source: "mr"          # Source for cluster utilization metrics (mr, ms, or ss)
    cluster_cpu_pct_target: 0.6        # Target CPU utilization percentage
    cluster_memory_pct_target: 0.6     # Target memory utilization percentage
    worker_pods_grace_period_sec: 120  # Grace period for worker pods termination
    node_labels:                       # Node labels for this pool
      deno.com/pool: default
    # lscfuse_startup_snapshot_max_size: "67108864" # Optional LSCFUSE startup snapshot max size
    # worker_tolerations: []           # Optional tolerations for worker pods
    # worker_node_affinities: []       # Optional node affinities for worker pods

lscached:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: lscached-serve
          topologyKey: "kubernetes.io/hostname"
  tolerations: []

proxy:
  use_proxy_protocol: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi
  autoscaler:
    minReplicas: 1
    maxReplicas: 10
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: proxy
          topologyKey: "kubernetes.io/hostname"
  tolerations: []

dnsmasq:
  upstreamServers:
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - 1.0.0.1
  resources:
    requests:
        cpu: 100m
        memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  nodeSelector: {}

compute_pops:
  - self

karpenter:
  ec2NodeClass:
    isolateWorkers:
      kubelet:
        maxPods: 205
  nodePool:
    isolateWorkers:
      expireAfter: 4h
      single_az:
        enabled: false
        zoneName: ap-northeast-1a
    stableWorkload:
      expireAfter: 710h
      single_az:
        enabled: false
        zoneName: ap-northeast-1a
