# Copyright Deno Land Inc. All Rights Reserved. Proprietary and confidential.

priorityClasses:
  enabled: true

storageClasses:
  enabled: true

clusterRBAC:
  enabled: true

controller:
  isolate_worker:
    tolerations:
    - key: deno.com/workloads
      operator: Exists
      effect: NoSchedule
    node_affinities:
    - key: deno.com/workloads
      operator: In
      values: ['isolate-workers']

lscached:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: lscached-serve
          topologyKey: "kubernetes.io/hostname"
  tolerations: []

proxy:
  use_proxy_protocol: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi
  autoscaler:
    minReplicas: 1
    maxReplicas: 10
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: proxy
          topologyKey: "kubernetes.io/hostname"
  tolerations: []

dnsmasq:
  upstreamServers: 
  - 8.8.8.8
  - 8.8.4.4
  - 1.1.1.1
  - 1.0.0.1
  resources: 
    requests:
        cpu: 100m
        memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
  nodeSelector: {}

compute_pops:
  - self

karpenter:
  ec2NodeClass:
    isolateWorkers:
      kubelet:
        maxPods: 205
  nodePool:
    isolateWorkers:
      expireAfter: 4h
      single_az:
        enabled: false
        zoneName: ap-northeast-1a
    stableWorkload:
      expireAfter: 710h
      single_az:
        enabled: false
        zoneName: ap-northeast-1a
